In [2]:
import numpy as np

# NumPy関数

In [3]:
x = np.zeros(shape=(2,3), dtype = float)
 # 要素が全て0の配列. shapeで形状を, dtypeでデータ型を指定する
 # ちなみに、配列の形状を取得するには、np.shapeを用いる
y = np.zeros_like(a=x)
 # xと同じ形状, データ型で要素が全て0の配列

In [4]:
a = np.arange(start=0, stop=10, step=2, dtype=int) 
  # 始点, 終点, 分割幅で指定された等差数列. 終点は含まない. 
  # 引数を1つ(n)だけ指定すると、0,1,...,n-1の連番となる
a = np.linspace(start=0, stop=10, num=51, endpoint=True)
  # 始点, 終点, 分割数で指定された等差数列.
  # 終点をデフォルトで含むが、endpointで指定可能. 
  # retstep=Trueとすると, 差分も同時出力される

In [5]:
a = np.eye(N=10, M=None, k=0, dtype=float) 
  # N次元の単位行列を返す. Mを指定すると列の数を変更できる
  # kでオフセットを指定できる(k>0で上三角, k<0で下三角側へシフト)
a = np.diag(v=np.arange(10), k=1)
  # ベクトルvを対角要素とする対角行列を生成(オフセットも指定可能)

In [6]:
x, y = np.array([1, 4, 2, 2]), np.array([5, 6, 7, 8])
a = np.append(arr=x, values=y, axis=None)  # 2つの配列の結合
  # 多次元配列をインプットとするときは、結合軸をaxisで指定する
a = np.reshape(a=x, newshape=(2, 2))  # 配列の形状を任意に変換
  # np.resizeを用いるとトータスサイズの変更も許される
a = np.ravel(x)  # 多次元配列を1次元配列に変換
                 # 対応するndarrayメソッドはflatten()

In [7]:
a, b = np.meshgrid(np.arange(5), np.arange(3), indexing='ij')
  # d個の一次元配列からd次元メッシュを生成
  # indexing='ij'と'xy'で行列/デカルトインデックスを変更可能
  # 以下は上の定義と等価
a, b = np.mgrid[0:5,0:3]

In [8]:
a = np.flip(m=x, axis=None)
  # 配列を(全次元で)逆順にする. 多次元の場合はaxisを指定可能
a = np.split(ary=x, indices_or_sections=2, axis=0)
  # 配列を分割する. indices_or_sectionsをintで指定すると等間隔, 
  # 配列にすると, 区切りを入れるインデックスの指定と解釈される
  # np.array_splitだと, int指定値で割り切れない場合も分割される
a = np.unique(ar=x, axis=None)
  # arから重複要素を削除した配列を取得 (axis指定で多次元も可能)
  # return_index, return_reverse, return_count=Trueでそれぞれ
  # arからaを作る, aからarに戻すインデックス, 重複数を同時取得
a = np.roll(a=x, shift=2, axis=None)
  # 配列aをshift分巡回させる. 多次元の場合もaxisを指定できる. 
a = np.sort(a=x, axis=-1, kind=None)
  # 配列aをソートする. axisで軸を, kindでアルゴリズムを指定できる
z = np.array([x,y])
a = np.transpose(a=z, axes=(1,0)) 
  # 配列zの軸を自由に入れ替える. 多次元でも同様. 
  # 2次元であればndarrayメソッドの.Tが便利
a = np.trace(a=z, offset=0, axis1=0, axis2=1)
  # 行列のトレースを計算. N x M行列の場合は小さい方の次元までの和
  # offsetやトレースをとるaxis(1,2)を指定可能
a = np.diagonal(a=z, offset=0, axis1=0, axis2=1)
  # 対角成分を抜き出し、配列として取得. offsetなどはtraceと同様
  # np.diagも2次元配列に対しては対角成分の配列を返す

In [9]:
a = np.nonzero(a=x<3)
  # nonzero要素を取得. 上のように条件文と組み合わせることが多い. 
a = np.where(x==2, 9, 0)
  # 条件式(x==2)を満たす要素を9、他を0で置き換える
  # 条件式を満たすxの要素のみ置き換えたければ、第三引数をxとする
a = np.argmin(a=x, axis=None)
  # 配列aの最小値のインデックスを取得. np.argmaxも同様
  # 最小値や最大値そのものを取得するにはnp.amin, np.amaxを用いる

In [24]:
x = np.reshape(np.arange(25), (5,5))
a = x[0, :]     # 2次元配列xの0行目を取得. x[:, 0]だと0列目
a = x[1:4, 2:3] # xの1,2,3行, 2,3列で構成される3x2行列を取得
a = x[[0,2]]    # xの0,2行で構成される2x5行列を取得
a = x[(0,2)]    # タプルだと普通に(0,2)要素を取得する
a = x[[0,1,2],[2,3,2]] # 2次元配列から1次元配列を取得
  # この例だと(0,2), (1,3), (2,2)要素を並べた1次元配列が取得できる
a = x[x<5] # 比較演算子を用いたインデックス指定.
  # この例だと要素が5未満のインデックスを取得し, 指定に用いている
a = x[np.ix_([0, 1], [1, 2, 4])] # np.ix_によるインデックス指定.
  # この例だと配列xの0,1行, 1,2,4列の2x3行列を取得する

In [11]:
x, y = np.linspace(0,1,3), np.geomspace(1,10,3)
a = np.sum(a=x, axis=0) # aの和を取得. axis指定も可能. 
  # 同様の関数に, 積:prod, 平均:average, 分散:varなどがある
a = np.cumsum(a=x, axis=0) # aの累積和配列を取得
a = np.diff(a=x, n=1)      # 差分配列を取得
  # n=1でa[i]=x[i+1]-x[i], n=2でa[i]=x[i+2]-2x[i+1]+x[i]など
a = np.around(a=x, decimals=2) # 要素ごとdecimals桁で四捨五入
  # 整数に丸める場合, 丸め方に応じてfloor, ceil, trancなどがある
a = 2.0*x              # 全ての要素に係数をかける.  
  # 剰余x%cや商x//cも要素ごとに計算される (x=x%c+c*(x//c))
a = x*y                # 要素ごとの積
a = x**3               # 要素ごとの累乗  
a = np.sin(x)          # 要素ごとのsin関数の計算
  # cos, tan, sinh, cosh, tanh, exp, logなども同様に使用できる
  # 逆三角関数はarccos, arcsin, arctanなど. 
  # arctan2(y,x)はx, yに対応する角度を[-pi,pi)で返す
a = np.dot(x,y)      # ベクトルの内積
a = np.cross(x, y)   # ベクトルの外積(最終軸の次元は2か3)
a = x + 1j*y         # 要素ごとの和. 複素数のndarrayに対して, 
  # np.conj(a), np.real(a), np.imag(a), np.abs(a)などが可能
a = x[:,None] + y[None,:]
  # a_ij=x_i + y_jを要素とする2次元配列を所得する
a = np.outer(x, y)
  # a_ij=x_i * y_jを要素とする2次元配列を所得する
a = 2 + x 
  # スカラー量との演算は2 => 2*np.ones(a.shape)と解釈される

In [13]:
# numpy.randomモジュールの使用例
a = np.random.rand(2, 3)
  # [0,1)の一様乱数配列(この例だと2x3)を生成.
  # randnとすると標準正規分布に従う乱数配列を生成
a = np.random.randint(low=1, high=5, size=(2,3))
  # [low,high]間の一様整数乱数の配列(形状はsizeで指定)を生成
a = np.random.normal(loc=1, scale=2, size=(2,3))  
  # 平均loc, 標準偏差scaleの正規分布に従う乱数を生成
  # 分布に応じてbinomial, beta, gamma, chisquareなども利用可能

# numpy.linalgモジュールの使用例
x = np.linspace(0,3,4).reshape(2,2)
a = np.linalg.inv(x) # 逆行列の計算
a = np.linalg.det(x) # 行列式の計算
a = np.linalg.solve(a=x, b=np.ones(2)) # Ay=bの解yを求める
a, b = np.linalg.eig(x)  # 固有値, 固有ベクトルをタプルで取得
 # 実対称・エルミート行列の場合はeighを用いる
 # 固有値だけを取得したい場合はeigvals, eigvalshなどを用いる
x = np.linspace(0,10,40).reshape(10,2,2)
a, b = np.linalg.eig(x)
 # 複数の行列の対角化をしたい場合は、多次元配列として渡す
 # linalg.solveで複数のベクトルbを扱いたい場合も同様

# numpy.fftモジュールの使用例
x = np.exp(2j*np.pi*np.arange(0,10)/10)
a = np.fft.fft(a=x, axis=0) # 配列aのフーリエ変換を計算
b = np.fft.ifft(a=a, axis=0) # 配列aの逆フーリエ変換を計算
 # 多次元のフーリエ変換を行うにはfftn, ifftnを用いる

# SciPy関数

In [25]:
import numpy as np
from scipy.integrate import quad, simps, solve_ivp
f = lambda x, a : np.sin(a*x)
sol = quad(func=f, a=0, b=np.pi, args=(1,), full_output=1)
  # 関数funcをaからbまで積分する. funcへの引数をargsで指定
  # 戻り値は(値,誤差)のタプル
  # full_output=1とすると収束に関する情報が加わる
  # epsabsとepsrelで絶対・相対許容誤差をそれぞれ指定できる
print(sol[0], sol[1])

x = np.linspace(0, np.pi, 100)
sol = simps(y=f(x, 1), x=x, dx=1.0, axis=-1)
  # 配列yを積分する. 評価点xは配列として与えるか, dxを指定する
  # dxはx=Noneのとき(xを指定しない場合)のみ有効
  # 多次元配列については積分軸をaxisで指定できる
print(sol)

f = lambda t, y, a : [y[1], -a*y[0]]
t = np.linspace(0, 2*np.pi, 3)
sol = solve_ivp(fun=f, t_span=(t[0],t[-1]), y0=[0,1],\
  method='RK45', t_eval=t, args=(1,), rtol=1e-10, atol=1e-10)
  # dy/dt=f(t,y)の形の微分方程式を初期値y(t0)=y0のもとで解く
  # t_spanで積分範囲, methodでアルゴリズム, argsでfの引数を指定
  # t_evalで結果を出力する時刻を指定
  # atol, rtolで絶対・相対許容誤差を指定できる
print(sol.y, sol.success)
  # t_evalで評価されたyはsol.yに格納されている
  # sol.sucessで計算がきちんと収束したか確認できる

2.0 2.220446049250313e-14
1.9999999690165366
[[ 0.00000000e+00 -1.90140959e-11  1.90226272e-11]
 [ 1.00000000e+00 -1.00000000e+00  1.00000000e+00]] True


In [ ]:
import numpy as np
import scipy.sparse as sp
# ndarrayからcsr形式の疎行列を生成する
A = np.random.rand(100,100)
A[A>1/100] = 0
A_sp = sp.csr_matrix(A) 
#print(A_sp)

# 非零要素の値, 行列インデックスからcsr形式の疎行列を生成する
data  = [1., 2., 3., 4., 5., 10.]
row = [0, 0, 1, 2, 2, 2]
col = [2, 3, 3, 2, 4, 4]
A_sp = sp.coo_matrix((data, (row, col)), shape=(5, 5))
A_sp = sp.csr_matrix(A_sp)
print(A_sp)

# 対角的な素行列に関しては、以下のように生成方法がある
B_sp = sp.eye(2, k=1, dtype=float)
C_sp = sp.diags([np.arange(3), np.arange(2)], offsets=[0,1])
  # 複数の一次元配列から対角的な行列を生成
D_sp = sp.block_diag((B_sp, C_sp))
  # 複数の疎行列をブロックとする対角行列を生成
  # eye, diagsの戻り値はdia形式, block_diagの戻り値はcoo形式
D_sp = D_sp.tocsr()

  (0, 2)	1.0
  (0, 3)	2.0
  (1, 3)	3.0
  (2, 2)	4.0
  (2, 4)	15.0


In [ ]:
X_sp = A_sp * D_sp          # 疎行列-疎行列積
X_sp = A_sp.multiply(D_sp)  # 疎行列同士の要素積
X_sp = A_sp + D_sp          # 疎行列同士の和
x = A_sp*np.linspace(0,1,5) # 疎行列-密ベクトル積
X_sp = A_sp.sin()           # 要素ごとにsinを計算
  # この他、arcsin, sqrt, power, conj, argmin, minなど様々な
  # メソッドを同様の形式で使用することができる
X_sp[0,2]=0                 # 0,2要素を0とする.
  # このような直接的な要素の変更はlil形式で行う方が望ましい
X_sp.eliminate_zeros()      # 零要素を取り除いて置き換え
data = X_sp.data     
row, col = X_sp.nonzero()   # 非零要素の行列インデックスを取得
X = X_sp.toarray()          # ndarrayクラスに変換
print(data)

[ 0.90929743  0.14112001 -0.7568025   0.65028784]


In [ ]:
vecs = [2*np.ones(10), -np.ones(9), -np.ones(9)]
A_sp = sp.diags(vecs, offsets = [0,1,-1])
eig, vec = sp.linalg.eigsh(A_sp, k=3, which='SA')
  # 実対称/エルミート疎行列A_spの固有値, 固有ベクトルを計算する
  # whichで指定した順にそってk個まで計算し、出力する
  # whichは'LM', 'SM', 'LA', 'SA'が指定可能で、
  # Lは降順, Sは昇順を表し, M, Aは絶対値および値を表す
  # v0で対角化に用いる初期ベクトルを設定することもできる
print(eig)

def Av(v):
    ans = 2*v - np.roll(v,1) - np.roll(v,-1)
    ans[0], ans[-1] = ans[0]+v[-1], ans[-1]+v[0]
    return ans
LO = sp.linalg.LinearOperator((10,10), matvec=Av)
eig, vec = sp.linalg.eigsh(LO, k=3, which='SA')
  # 疎行列の代わりに行列作用素として渡すこともできる.
  # LinearOperatorは第一引数で行列の形状を指定し,
  # matvecなどで対応する演算を定義する
print(eig)

b = np.ones(10)
x, tol = sp.linalg.cg(A=LO, b=b)
  # 線型方程式Ax=bを解く. Aは疎行列でもLinearOperator
  # でも良いが, 正定値対称である必要がある
print(x)

[0.08101405 0.31749293 0.69027853]
[0.08101405 0.31749293 0.69027853]
[ 5.  9. 12. 14. 15. 15. 14. 12.  9.  5.]


In [ ]:
from scipy.optimize import root_scalar, root, minimize
f = lambda x, a : a*x**2 - 4
sol = root_scalar(f,args=(1,),method='bisect',bracket=(0, 5))
  # スカラー関数の根の探索. この例ではbisectで二分法を指定している
  # 二分法を指定する場合は根の探索範囲をbracketで指定する
  # xtol, rtolで絶対・相対許容誤差をそれぞれ指定できる
print(sol.root, sol.converged, sol.function_calls)
  # 戻り値はRootResultsクラスで, rootに解が格納されている
  # 他, convergedは収束判定, function_callsは関数の評価回数など
fp = lambda x, a : a*2*x
sol = root_scalar(f,args=(1,),method='newton',x0=-4,fprime=fp)
  # newtonを用いるなら初期値x0を指定する必要がある
  # fprimeにfの微分を指定, 指定がなければ数値的に評価する
print(sol.root, sol.converged, sol.function_calls)

f = lambda x, a: [x[0]**2+x[1]**2-a, x[1]-x[0]**3]
fp = lambda x, a: [[2*x[0], 2*x[1]],[-3*x[0]**2, 1]]
sol = root(f, x0=[2,2], args=(1,), method='hybr', jac=fp)
  # 多次元関数の根の探索. デフォルトのmethod(hybr)を用いている
  # hybrx0で初期値, jacでヤコビアンを指定できる
  # broyden1のようにヤコビアンの数値評価を前提とするmethodでは
  # jacの指定方法が異なるので注意(指定しなくても良い)
print(sol.x, sol.success, sol.nfev)
#>> [0.82603136 0.56362416] True 14

f = lambda x : (x[0] + 1)**2 + (x[1] - 2)**2
sol = minimize(f, x0=(0,1))
  # f(x)を最小化するxを探す. 境界や制限も条件として付与できる
  # デフォルトでは条件に応じてBFGS, L-BFGS-B, SLSQPを用いる
  # jac, hessでヤコビアンやヘッシアン, tolで許容誤差の指定など
print(sol.x)
#>> [-1.00000002  1.99999999]

  # 境界に条件をつける場合は以下のようにする.
bnds = ((0, None), (0, None)) # x[0], x[1]ともに0以上
sol = minimize(f, x0=(0,1), bounds=bnds)
print(sol.x)
#>> [0. 2.]

  # 制限はtype(等号or不等号), 関数などを指定可能
  # 以下の例はx[0]-x[1]=0という制限を与える
cons = ({'type': 'eq', 'fun': lambda x: x[0] - x[1]})
sol = minimize(f, x0=(0,1), constraints=cons)
print(sol.x)
#>> [0.5 0.5]

1.9999999999993179 True 44
-2.0 True 12
[0.82603136 0.56362416] True 14
[-1.00000002  1.99999999]
[0. 2.]
[0.5 0.5]
